const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const modalPath = path.join(__dirname, 'CreateModelModal.tsx')
const apiPath = path.join(__dirname, '../services/api.ts')
const modalSource = fs.readFileSync(modalPath, 'utf8')
const apiSource = fs.readFileSync(apiPath, 'utf8')

assert.match(apiSource, /export type MetadataSpecPayload = \{/, 'api should expose typed metadata creation payload')
assert.match(apiSource, /category_code: string/, 'metadata payload should require category_code')
assert.match(apiSource, /spec_name: string/, 'metadata payload should require spec_name')
assert.match(apiSource, /spec_type: string/, 'metadata payload should require spec_type')
assert.match(apiSource, /export const createMetadata = \(data: MetadataSpecPayload\)/, 'createMetadata should accept MetadataSpecPayload')
assert.doesNotMatch(modalSource, /新建字段要求/, 'create-model modal should not own field requirement controls')
assert.doesNotMatch(modalSource, /搜索字段要求/, 'create-model modal should not own field requirement search')
assert.doesNotMatch(modalSource, /onMetadataChanged/, 'create-model modal should not manage field requirement refresh')
assert.doesNotMatch(modalSource, /createMetadata/, 'create-model modal should not create metadata records')
assert.match(modalSource, /品类属性 \/ 品类字段要求/, 'create-model modal should still render the category field block')
