const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const modalPath = path.join(__dirname, 'CreateModelModal.tsx')
const apiPath = path.join(__dirname, '../services/api.ts')
const modalSource = fs.readFileSync(modalPath, 'utf8')
const apiSource = fs.readFileSync(apiPath, 'utf8')

assert.match(apiSource, /export type MetadataSpecPayload = \{/, 'api should expose typed metadata creation payload')
assert.match(apiSource, /category_code: string/, 'metadata payload should require category_code')
assert.match(apiSource, /spec_name: string/, 'metadata payload should require spec_name')
assert.match(apiSource, /spec_type: string/, 'metadata payload should require spec_type')
assert.match(apiSource, /export const createMetadata = \(data: MetadataSpecPayload\)/, 'createMetadata should accept MetadataSpecPayload')
assert.match(modalSource, /createMetadata/, 'modal should import and call createMetadata')
assert.match(modalSource, /onMetadataChanged\?: \(\) => Promise<void> \| void/, 'modal props should expose onMetadataChanged callback')
assert.match(modalSource, /const \[specSearch, setSpecSearch\] = useState\(''\)/, 'modal should keep local spec search state')
assert.match(modalSource, /filteredMetadataSpecs/, 'modal should render filtered metadata specs')
assert.match(modalSource, /新建字段要求/, 'modal should expose new field requirement action')
assert.match(modalSource, /搜索字段要求/, 'modal should expose current-category field requirement search')
assert.match(modalSource, /category_code: currentCategoryCode/, 'new metadata payload should use current category code')
assert.match(modalSource, /await onMetadataChanged\?\.\(\)/, 'modal should request metadata refresh after creation')
