const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

const source = fs.readFileSync(path.join(__dirname, 'index.tsx'), 'utf8')
const exportColsSource = source.match(/const exportCols = \[[\s\S]*?\n  \]/)?.[0] ?? ''

assert.match(source, /getExportFilters/, 'export page should load export filter options from the export API')
assert.doesNotMatch(source, /useCategoryOptions/, 'export page should not use the global category list for export filters')
assert.doesNotMatch(source, /listCleanJobs\(/, 'export page should not derive export filters from clean job list status')
assert.match(source, /const \[selectedMonths, setSelectedMonths\]/, 'export page should keep selected months')
assert.match(source, /const \[selectedCategoryCode, setSelectedCategoryCode\]/, 'export page should keep selected category')
assert.match(source, /const \[selectedPlatforms, setSelectedPlatforms\]/, 'export page should keep selected platforms')
assert.match(source, /months:\s*selectedMonths/, 'export trigger should submit selected months')
assert.match(source, /category_code:\s*selectedCategoryCode/, 'export trigger should submit selected category')
assert.match(source, /platforms:\s*selectedPlatforms/, 'export trigger should submit selected platforms')
assert.match(source, /visibleCategories\.map\(category => \(\{ value: category\.code, label: category\.name \}\)\)/, 'category options should map visible API code/name fields to Select value/label')
assert.match(source, /options=\{categoryOptions\}/, 'category Select should use derived category options')
assert.match(source, /placeholder="选择月度"/, 'export page should render month filter')
assert.match(source, /placeholder="选择品类"/, 'export page should render category filter')
assert.match(source, /placeholder="选择平台"/, 'export page should render platform filter')
assert.match(exportColsSource, /title: '导出范围'/, 'export history should keep scope column')
assert.match(exportColsSource, /title: '状态'/, 'export history should keep status column')
assert.match(exportColsSource, /title: '提交时间'/, 'export history should keep created time column')
assert.doesNotMatch(exportColsSource, /title: '文件名前缀'/, 'export history should not show filename prefix column')
assert.doesNotMatch(exportColsSource, /title: '已匹配行'/, 'export history should not show matched row column')
assert.doesNotMatch(exportColsSource, /title: '待确认行'/, 'export history should not show pending row column')
