const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

const source = fs.readFileSync(path.join(__dirname, 'index.tsx'), 'utf8')

assert.match(source, /getExportFilters/, 'export page should load export filter options from the export API')
assert.doesNotMatch(source, /useCategoryOptions/, 'export page should not use the global category list for export filters')
assert.doesNotMatch(source, /listCleanJobs\(/, 'export page should not derive export filters from clean job list status')
assert.match(source, /const \[selectedMonths, setSelectedMonths\]/, 'export page should keep selected months')
assert.match(source, /const \[selectedCategoryCode, setSelectedCategoryCode\]/, 'export page should keep selected category')
assert.match(source, /const \[selectedPlatforms, setSelectedPlatforms\]/, 'export page should keep selected platforms')
assert.match(source, /months:\s*selectedMonths/, 'export trigger should submit selected months')
assert.match(source, /category_code:\s*selectedCategoryCode/, 'export trigger should submit selected category')
assert.match(source, /platforms:\s*selectedPlatforms/, 'export trigger should submit selected platforms')
assert.match(source, /filterOptions\.categories\.map\(category => \(\{ value: category\.code, label: category\.name \}\)\)/, 'category options should map API code/name fields to Select value/label')
assert.match(source, /placeholder="选择月度"/, 'export page should render month filter')
assert.match(source, /placeholder="选择品类"/, 'export page should render category filter')
assert.match(source, /placeholder="选择平台"/, 'export page should render platform filter')
