const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')

const pageSource = fs.readFileSync(path.join(__dirname, 'index.tsx'), 'utf8')
const apiSource = fs.readFileSync(path.join(__dirname, '../../services/api.ts'), 'utf8')
const historyColumnsSource = pageSource.match(/const historyColumns = \([\s\S]*?\n\]/)?.[0] ?? ''

assert.match(apiSource, /export interface UploadDownloadJob/, 'API should declare upload download job type')
assert.match(apiSource, /export const createUploadDownloadJob = \(fileId: number\) =>/, 'API should export createUploadDownloadJob helper')
assert.match(apiSource, /api\.post<UploadDownloadJob>\(`\/upload\/files\/\$\{fileId\}\/download-jobs`\)/, 'createUploadDownloadJob should post to upload download job endpoint')
assert.match(apiSource, /export const listUploadDownloadJobs = \(params\?: \{ file_ids\?: number\[\] \}\) =>/, 'API should export listUploadDownloadJobs helper')
assert.match(apiSource, /file_ids: params\.file_ids\.join\(','\)/, 'listUploadDownloadJobs should serialize visible file ids')
assert.match(apiSource, /export const getUploadDownloadJobUrl = \(jobId: number\) => `\/api\/upload\/download-jobs\/\$\{jobId\}\/download`/, 'API should expose ready job download URL helper')

assert.match(pageSource, /createUploadDownloadJob/, 'Upload page should start background download jobs')
assert.doesNotMatch(pageSource, /downloadUploadFile\(id\)/, 'Upload page should not use foreground blob download on row click')
assert.match(pageSource, /listUploadDownloadJobs/, 'Upload page should refresh upload download jobs')
assert.match(pageSource, /getUploadDownloadJobUrl/, 'Upload page should render ready job download URLs')
assert.match(pageSource, /const \[downloadJobsByFileId, setDownloadJobsByFileId\]/, 'Upload page should track download jobs by upload file id')
assert.match(pageSource, /setInterval\(\(\) => \{[\s\S]*refreshDownloadJobs\(\)[\s\S]*\}, 15000\)/, 'Upload page should silently refresh download jobs every 15 seconds')
assert.match(pageSource, /clearInterval\(downloadJobsPollRef\.current\)/, 'Upload page should clean up download job polling')
assert.match(historyColumnsSource, /下载状态/, 'Upload history should include a download status column')
assert.match(historyColumnsSource, /<Progress/, 'Upload history should render progress for running download jobs')
assert.match(historyColumnsSource, /下载文件/, 'Upload history should render ready download link')
assert.match(historyColumnsSource, /startDownloadJob\(row\.id\)/, 'Download action should start background job for the row')
